//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CH06.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASMT_User
    {
        public string UserEmpID { get; set; }
        public string UserID { get; set; }
        public string UserName { get; set; }
        public string DeptID { get; set; }
        public string DeptName { get; set; }
        public string ExtNumber { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> OnBoardDate { get; set; }
        public string JobTitle { get; set; }
        public string Manager_lv01 { get; set; }
        public string Role { get; set; }
        public string OnJob { get; set; }
        public Nullable<System.DateTime> UpdTime { get; set; }
    }
}
